# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Chaitanya Jadhav
tagline: ""
description: ""
url: chaitanyajadhav.com
baseurl: /
emailme: chaitanya.jadhav15@hotmail.com
#TODO - get this working someday
# # github_username: "indicium15"
# linkedin_username: "chaitanya-jadhav-134392191"

author:
  name: "Chaitanya Jadhav"

plugins: [jekyll-paginate]
paginate: 5

# Custom vars
version: 2.1.0

disqus:
  shortname: chaitanyajadhav-com-1
